name: Custom Environment Variable
on: [push]

jobs:
  custom-env-var:
    runs-on: ubuntu-latest
    env:
      echo "JOB_LEVEL_ENV_VAR=$RANDOM" >> "$GITHUB_ENV": HELLO FROM JOB
    steps:
        # This is the way to set an env variable dynamically
        # This new env var is now available for the subsequents steps
      - name: Set env var
        run: |
             echo "NEW_ENV_VAR=$(date)" >> "$GITHUB_ENV"

      - name: Override env var
        run: |
            echo "JOB_LEVEL_ENV_VAR=$RANDOM" >> "$GITHUB_ENV"
        
        # Set env variables in multiple lines
      - name: Multiline env var
        run: |
            DELIMITER=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
            echo "RANDOM_JOKE<<$DELIMITER" >> "$GITHUB_ENV"
            echo "Here is a joke: " >> "$GITHUB_ENV"
            curl -s https://icanhazdadjoke.com/ >> "$GITHUB_ENV"
            echo "" >> "$GITHUB_ENV"
            echo "$DELIMITER" >> "$GITHUB_ENV"
        
      - name: log custom env vars
        run: |
            echo $NEW_ENV_VAR
            echo $JOB_LEVEL_ENV_VAR
            echo $RANDOM_JOKE_ENV_VAR
            