name: Simple Action
on: [push]

jobs:
    simple-action:
        runs-on: ubuntu-latest
        steps:
            - name: Greet
              id: greet_id
              uses: actions/hello-world-javascript-action@v1.1 
              with:
                  who-to-greet: ${{ github.actor }}
            
            - name: Log greeting time
              run: echo "${{ steps.greet_id.outputs.time }}"